### ISSUE TITLE
Conflicting version of pyyaml

### ISSUE THREAD

**Issue by raghavkarol** [alertlogic/alcli#49]
Conflicting version of pyaml
https://github.com/alertlogic/alcli/blob/89f80196398683ef7400c59365f740ce5c7163b7/requirements.txt#L7

https://github.com/alertlogic/alertlogic-sdk-definitions/blob/master/requirements.txt

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
alcli 1.0.46 requires pyyaml==5.1.2, but you have pyyaml 5.4 which is incompatible.
```

Should we do away with the requirement for a specific version?

**Comment by raghavkarol** [comment]
@anton-b

**Comment by anton-b** [comment]
looking

**Comment by anton-b** [comment]
resolved
